spin_version = "1"
authors = ["Chris Matteson <chris.matteson@gmail.com>"]
description = "An example app to demonstrate docker and kubernetes"
name = "docker"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "docker"
source = "target/wasm32-wasi/release/docker.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
